### ISSUE TITLE
High cpu usage

### ISSUE THREAD

**Issue by ragadeeshu** [hsanjuan/go-dcc#4]
When running the dccpi cmdline application on a pi model 3 it consumes an entire core running at 1.2ghz with a constant 99% gpu load. Is this expected? It seems to use even more resources than the python variant.

**Comment by hsanjuan** [comment]
This might be intended.

You see, the DCC protocol requires putting packages on the wire almost constantly. In Python, calls to Sleep() may take way longer than intended (https://github.com/hsanjuan/dccpi/blob/master/dccpi/dcc_controller.py#L182). Thread management (along with the execution slowness) makes it very difficult to strictly follow the DCC spec in the Python/C implementation. This all also resulted in a visible delay between calling a new command and it reaching the locomotives. And if it works after all it's probably because DCC decoders allow for much leeway, keeping things going when no packets are sent on the tracks.

In Go, we are more certain to be sleeping the right intervals, and that may mean more CPU usage, but also a more solid DCC implementation and responsiveness.

**Comment by ragadeeshu** [comment]
Ok, thank you for the response!
